[package]
name = "instory"
version = "0.1.0"
authors = ["Ruslan Fadeev <kinrany@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
uuid = { version = "0.8.2", features = ["serde"] }

[dev-dependencies]
anyhow = "1.0.40"
fehler = "1.0.0"
ureq = { version = "2.1.0", features = ["json"] }
